/**
 * The four defences DD6 step 4 asks for, each asserted as an observable
 * property of the bytes that come out — never as "the pipeline was configured
 * this way".
 *
 * The fixtures are generated by `sharp` itself rather than committed, which is
 * the only honest way to have a photo in this repository: `docs/policy/security.md`
 * and the `ui-proof` skill both refuse a real face in a stored artifact, and a
 * generated gradient exercises the same decoder.
 */

import sharp from "sharp";
import { DECODABLE_FORMATS, MAX_LONG_EDGE_PX, MAX_UPLOAD_BYTES, PUBLIC_QUALITY } from "#limits";
import { MAX_INPUT_PIXELS, reencodeForPublic } from "#reencode";

/** A plain raster of a given size, in a given container. */
function image(width: number, height: number) {
  return sharp({
    create: { width, height, channels: 3, background: { r: 180, g: 90, b: 40 } },
  });
}

describe("reencodeForPublic", () => {
  it.each(["jpeg", "png", "webp"] as const)("produces WebP from %s", async (format) => {
    const input = await image(400, 300)[format]().toBuffer();

    const { bytes } = await reencodeForPublic(input);

    expect((await sharp(bytes).metadata()).format).toBe("webp");
  });

  it("reports the format it found rather than one it was told", async () => {
    const input = await image(400, 300).png().toBuffer();

    expect((await reencodeForPublic(input)).sourceFormat).toBe("png");
  });

  /**
   * The EXIF defence, and the one worth the most. `withMetadata()` is absent
   * from the pipeline, so this asserts the consequence: a GPS tag on the way in
   * is not on the way out.
   */
  it("drops EXIF, and with it GPS", async () => {
    const withGps = await image(400, 300)
      .withExif({ IFD0: { Model: "a phone" }, IFD3: { GPSLatitude: "4/1 48/1 0/1" } })
      .jpeg()
      .toBuffer();

    // The fixture is only worth anything if it really carries what we claim.
    expect((await sharp(withGps).metadata()).exif).toBeDefined();

    const { bytes } = await reencodeForPublic(withGps);

    expect((await sharp(bytes).metadata()).exif).toBeUndefined();
  });

  /**
   * Orientation is the one EXIF tag whose loss is visible, so it is applied to
   * the pixels before the rest is dropped. A 6 (`rotate 90°`) photo that came
   * out landscape would mean `.rotate()` had been removed with the metadata.
   *
   * `withMetadata({ orientation })` rather than `withExif({ IFD0: { Orientation } })`,
   * which was the first fixture and was silently useless: sharp normalises the
   * tag on write, so the file came out as orientation 1 and the test passed a
   * rotated image nothing had rotated. Verified by reading the tag back below —
   * a fixture that does not carry what the test claims proves nothing.
   */
  it("applies the orientation tag to the pixels before dropping it", async () => {
    const sideways = await image(400, 200).withMetadata({ orientation: 6 }).jpeg().toBuffer();

    expect((await sharp(sideways).metadata()).orientation).toBe(6);

    const { width, height } = await reencodeForPublic(sideways);

    expect({ width, height }).toEqual({ width: 200, height: 400 });
    expect(
      (await sharp((await reencodeForPublic(sideways)).bytes).metadata()).orientation,
    ).toBeUndefined();
  });

  it("bounds the long edge whichever edge it is, and never upscales", async () => {
    const landscape = await reencodeForPublic(await image(4000, 2000).jpeg().toBuffer());
    const portrait = await reencodeForPublic(await image(2000, 4000).jpeg().toBuffer());
    const small = await reencodeForPublic(await image(240, 180).jpeg().toBuffer());

    expect(landscape.width).toBe(MAX_LONG_EDGE_PX);
    expect(portrait.height).toBe(MAX_LONG_EDGE_PX);
    expect({ width: small.width, height: small.height }).toEqual({ width: 240, height: 180 });
  });

  it("refuses bytes over the ceiling the presigned PUT is supposed to enforce", async () => {
    const oversized = Buffer.alloc(MAX_UPLOAD_BYTES + 1);

    await expect(reencodeForPublic(oversized)).rejects.toMatchObject({
      code: "photo_over_byte_ceiling",
    });
  });

  /**
   * The SVG defence. libvips will rasterise an SVG happily, so this is the one
   * case where the decoder succeeding is the failure — an SVG is a document
   * that can carry script for whatever renders it next, and the allowlist is
   * what stops one becoming a stored object.
   */
  it("refuses SVG, which the decoder is otherwise willing to rasterise", async () => {
    const svg = Buffer.from(
      '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64">' +
        '<script>fetch("//example.test")</script><rect width="64" height="64"/></svg>',
    );

    await expect(reencodeForPublic(svg)).rejects.toMatchObject({
      code: "photo_format_not_allowed",
    });
  });

  it("refuses bytes that are not an image at all", async () => {
    await expect(reencodeForPublic(Buffer.from("not a picture"))).rejects.toMatchObject({
      code: "photo_undecodable",
    });
  });

  /**
   * A polyglot: a real JPEG with a script payload appended. It decodes, so the
   * format allowlist passes it — and the defence that matters is the re-encode
   * itself, which rebuilds the file from pixels and leaves the appended bytes
   * nowhere.
   */
  it("re-encodes a polyglot down to its pixels, leaving the appended payload nowhere", async () => {
    const payload = '<script>alert("stored xss")</script>';
    const polyglot = Buffer.concat([await image(200, 200).jpeg().toBuffer(), Buffer.from(payload)]);

    const { bytes } = await reencodeForPublic(polyglot);

    expect(bytes.includes(payload)).toBe(false);
  });

  /**
   * The decompression bomb, driven through the real function rather than
   * through a pipeline the test configured — an earlier version built its own
   * `sharp(…, { limitInputPixels: 1 })` and so asserted nothing about
   * `reencodeForPublic` at all.
   *
   * A solid colour compresses to a few tens of kilobytes at any size, which is
   * the whole shape of the attack: a small file that declares an allocation
   * large enough to take the 1 GB machine (C34) with it. The refusal has to
   * arrive from the declared dimensions, before the raster exists.
   */
  it("refuses a declared size above the pixel ceiling, before allocating for it", async () => {
    const edge = Math.ceil(Math.sqrt(MAX_INPUT_PIXELS)) + 1_000;
    const bomb = await image(edge, edge).png({ compressionLevel: 9 }).toBuffer();

    expect(bomb.byteLength).toBeLessThan(MAX_UPLOAD_BYTES);

    await expect(reencodeForPublic(bomb)).rejects.toMatchObject({ code: "photo_undecodable" });
  });

  it("derives the pixel ceiling from the edge it targets, so raising one raises both", () => {
    expect(MAX_INPUT_PIXELS).toBe((MAX_LONG_EDGE_PX * 4) ** 2);
  });

  it("keeps SVG out of the decode allowlist, which is the whole of that defence", () => {
    expect(PUBLIC_QUALITY).toBeGreaterThan(0);
    expect(DECODABLE_FORMATS).not.toContain("svg");
  });
});
