-- Every Skill takes a group (ADR-0021).
--
-- Authored rather than generated, for the seed's reason: this is data, and a data
-- migration has no schema to be generated from. The column it fills arrives
-- nullable in the migration before it, and the `CHECK` in the one after.
--
-- **Each seed slug takes the heading it was written under in 0008**, derived by
-- reading that file's headings rather than retyped. **Anything the seed never
-- named goes to `other`**, which is what lets this run on a database that has
-- seen Admin promotions; such a row is regrouped by a later migration, since no
-- form moves a Skill between groups.

UPDATE "skill" SET "skill_group" = seeded.skill_group
FROM (VALUES
  ('home-cleaning',                  'home_and_laundry'),
  ('office-cleaning',                'home_and_laundry'),
  ('laundry-and-ironing',            'home_and_laundry'),
  ('window-cleaning',                'home_and_laundry'),
  ('vehicle-washing',                'home_and_laundry'),
  ('odd-jobs',                       'home_and_laundry'),
  ('building-caretaking',            'home_and_laundry'),
  ('home-cooking',                   'food'),
  ('traditional-cooking',            'food'),
  ('fast-food',                      'food'),
  ('kitchen-assistance',             'food'),
  ('baking-and-pastry',              'food'),
  ('table-service',                  'food'),
  ('bartending',                     'food'),
  ('barista-work',                   'food'),
  ('street-food-selling',            'food'),
  ('meat-preparation',               'food'),
  ('child-care',                     'care_and_teaching'),
  ('elder-care',                     'care_and_teaching'),
  ('patient-companionship',          'care_and_teaching'),
  ('injections-and-wound-care',      'care_and_teaching'),
  ('pet-care',                       'care_and_teaching'),
  ('school-tutoring',                'care_and_teaching'),
  ('language-tutoring',              'care_and_teaching'),
  ('dance-classes',                  'care_and_teaching'),
  ('fitness-training',               'care_and_teaching'),
  ('hairdressing',                   'beauty'),
  ('barbering',                      'beauty'),
  ('manicure-and-pedicure',          'beauty'),
  ('makeup',                         'beauty'),
  ('beauty-and-massage',             'beauty'),
  ('bricklaying',                    'building'),
  ('construction-labour',            'building'),
  ('rough-carpentry',                'building'),
  ('roofing',                        'building'),
  ('tiling',                         'building'),
  ('floor-installation',             'building'),
  ('plastering',                     'building'),
  ('painting',                       'building'),
  ('plumbing',                       'building'),
  ('gas-installation',               'building'),
  ('electrical-work',                'building'),
  ('glass-installation',             'building'),
  ('welding',                        'building'),
  ('locksmithing',                   'building'),
  ('refrigeration-repair',           'building'),
  ('furniture-making',               'furniture_and_textiles'),
  ('upholstery',                     'furniture_and_textiles'),
  ('dressmaking',                    'furniture_and_textiles'),
  ('clothing-repairs',               'furniture_and_textiles'),
  ('industrial-sewing',              'furniture_and_textiles'),
  ('knitting',                       'furniture_and_textiles'),
  ('shoe-repair',                    'furniture_and_textiles'),
  ('motorcycle-delivery',            'transport'),
  ('car-driving',                    'transport'),
  ('taxi-driving',                   'transport'),
  ('bus-driving',                    'transport'),
  ('truck-driving',                  'transport'),
  ('errands',                        'transport'),
  ('loading-and-moving',             'transport'),
  ('gardening',                      'farm_and_garden'),
  ('coffee-farm-work',               'farm_and_garden'),
  ('harvest-work',                   'farm_and_garden'),
  ('livestock-work',                 'farm_and_garden'),
  ('pest-control',                   'farm_and_garden'),
  ('vehicle-mechanics',              'repairs'),
  ('bicycle-repair',                 'repairs'),
  ('appliance-repair',               'repairs'),
  ('computer-repair',                'repairs'),
  ('phone-repair',                   'repairs'),
  ('antenna-and-camera-installation','repairs'),
  ('shop-assistance',                'commerce_and_office'),
  ('cashiering',                     'commerce_and_office'),
  ('market-selling',                 'commerce_and_office'),
  ('warehouse-work',                 'commerce_and_office'),
  ('bookkeeping',                    'commerce_and_office'),
  ('security-guarding',              'commerce_and_office'),
  ('event-organising',               'commerce_and_office'),
  ('event-setup',                    'commerce_and_office'),
  ('photography',                    'commerce_and_office'),
  ('video-recording',                'commerce_and_office'),
  ('live-music',                     'commerce_and_office'),
  ('local-guiding',                  'commerce_and_office'),
  ('data-entry',                     'remote_work'),
  ('call-centre-work',               'remote_work'),
  ('administrative-assistance',      'remote_work'),
  ('social-media-management',        'remote_work'),
  ('graphic-design',                 'remote_work'),
  ('transcription',                  'remote_work'),
  ('translation',                    'remote_work'),
  ('recycling-collection',           'recycling')
) AS seeded (slug, skill_group)
WHERE "skill"."slug" = seeded.slug;
--> statement-breakpoint
UPDATE "skill" SET "skill_group" = 'other' WHERE "skill_group" IS NULL;
