#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=23

# Runbook §§1–5 of docs/runbooks/recomencemos-go-live.md, for ticket #7.
#
# The document is written; running it is the work. These are the steps only a
# person can take: your accounts, your card, your DNS, your dashboards.
#
# Two deviations from the usual wizard habit, both load-bearing:
#
#   1. ENV_FILE is NOT .env. §1 forbids a repo .env outright, and the reason is
#      mechanical rather than stylistic: turbo.json declares `.env*` a `build`
#      input, so the file's content is hashed into the cache key and travels
#      with the artifact under remote caching. The facts file below holds only
#      non-secret values — an app name, a bucket, a domain — so re-runs are
#      pleasant. No secret is ever written to it, or anywhere else on disk.
#
#   2. There is an evidence transcript, and every check is a real command.
#      #7's last acceptance criterion asks for "a command and its output, not
#      an assertion that it was done", so `run` executes, shows, and appends.
#      `attest` is for the handful of things no command can prove: it records
#      the question AND the answer, so an unticked row is visibly unticked
#      rather than quietly absent.
#
# These helpers live BELOW the marker on purpose: the library above it is
# identical in every wizard and is never hand-edited.

ENV_FILE="${ENV_FILE:-.go-live-facts}"
EVIDENCE="${EVIDENCE:-.go-live-evidence.md}"

RUN_STATUS=0
RUN_OUTPUT=""
FLY_SET=()
DEFERRED=()

# evidence_init starts (or continues) the transcript for this run.
evidence_init() {
  {
    printf '\n---\n\n# Runbook 1-5 evidence\n\n'
    printf -- '- Run started: %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf -- '- Host: %s\n' "$(uname -sr)"
    printf -- '- Repo HEAD: %s\n\n' "$(git rev-parse --short HEAD 2>/dev/null || echo 'not a checkout')"
  } >> "$EVIDENCE"
  note "evidence → $EVIDENCE (gitignored; paste it on the ticket when you are done)"
}

# section "..." writes a heading into the transcript.
section() { printf '\n## %s\n' "$1" >> "$EVIDENCE"; }

# run "shown command" -- argv...
#
# The shown string and the executed argv are separate so that a connection
# string passed as an argument never reaches the transcript. That is the whole
# reason this takes two forms of the same command rather than one.
# Always returns 0; the exit status lands in $RUN_STATUS and the output in
# $RUN_OUTPUT, so `set -e` cannot end the wizard halfway through a section.
#
# $RUN_OUTPUT is what makes a check honest rather than merely printed: a stage
# branches on the bytes that went into the transcript, not on a second run of
# the same command and not on a value re-typed by the person being checked.
run() {
  local shown="$1"; shift
  [[ "${1:-}" == "--" ]] && shift
  local out status
  printf '  %s$ %s%s\n' "$DIM" "$shown" "$RESET"
  set +e
  out=$("$@" 2>&1)
  status=$?
  set -e
  printf '%s\n' "$out" | sed 's/^/    /'
  {
    # shellcheck disable=SC2016  # the `$ ` here is a literal prompt in the transcript, not an expansion
    printf '\n```console\n$ %s\n%s\n```\n' "$shown" "$out"
    (( status == 0 )) || printf '\n_exit status %s_\n' "$status"
  } >> "$EVIDENCE"
  RUN_STATUS=$status
  RUN_OUTPUT="$out"
  return 0
}

# run_value is $RUN_OUTPUT with surrounding whitespace stripped, for the checks
# whose whole answer is one token: a status code, a count.
run_value() { printf '%s' "$RUN_OUTPUT" | tr -d '[:space:]'; }

# record "Fact" "value" appends an attested fact — for the things a command
# cannot produce, such as an elapsed restore time read off a clock. The
# transcript labels these `(attested)` so a reader can tell a measurement from
# a statement at a glance; a section that claims commands should not be able to
# smuggle an assertion in looking like one.
record() {
  printf -- '\n- **%s** (attested): %s\n' "$1" "${2:-—}" >> "$EVIDENCE"
  printf '  %s✓ recorded%s %s: %s\n' "$GREEN" "$RESET" "$1" "${2:-—}"
}

# show_once NAME VALUE prints a generated secret to the screen, once, so it can
# be copied into the password manager.
#
# This exists because nothing else can produce the value again. `fly secrets`
# prints names and digests and never a value, and these two are generated here
# rather than issued by a dashboard you could return to. A generated secret
# staged and never shown is a secret nobody holds -- and for the auth secret
# that is not a lost string but every Admin second factor, since it encrypts
# the TOTP secrets and backup codes at rest.
#
# It is deliberately NOT written to disk. `$EVIDENCE` is pasted onto a public
# ticket and `$ENV_FILE` is a repo path; the screen is the one channel here
# that ends when the terminal does.
show_once() {
  local name="$1" value="$2"
  [[ -z "$value" ]] && return 0
  printf '\n  %s%s╔══ %s — shown once, and nowhere else ══%s\n' "$BOLD" "$YELLOW" "$name" "$RESET"
  printf '  %s%s║%s  %s\n' "$BOLD" "$YELLOW" "$RESET" "$value"
  printf '  %s%s╚═══════════════════════════════════════%s\n\n' "$BOLD" "$YELLOW" "$RESET"
  step "Copy it into the password manager NOW, before this screen clears."
  note "It is not written to any file, and no command can print it back."
  pause "Copied? Press Enter."
}

# attest "question" is a confirm whose question AND answer both land in the
# transcript. §4's inbox check is the case this exists for: the runbook says it
# is the step most likely to be ticked without being done.
attest() {
  local answer=no
  confirm "$1" && answer=yes
  printf -- '\n- **%s** → **%s**\n' "$1" "$answer" >> "$EVIDENCE"
  [[ "$answer" == yes ]]
}

# defer "row" "reason" records a runbook row that cannot be done yet, with the
# reason. A deferred row is not a done row and does not read as one.
defer() {
  DEFERRED+=("$1 — $2")
  SKIPPED+=("$1 — $2")
  printf -- '\n- **DEFERRED — %s:** %s\n' "$1" "$2" >> "$EVIDENCE"
  warn "deferred: $1"
  note "  $2"
}

# fly_secret NAME VALUE stages a secret on the Fly app. The value goes in over
# stdin via `fly secrets import`, never as an argument, so it never reaches
# `ps` output or this terminal's history. --stage because §1 runs before
# anything has deployed, so there is no machine to restart yet.
fly_secret() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    SKIPPED+=("fly secret $name — nothing entered this run")
    warn "skipped $name (nothing entered)"
    return 0
  fi
  if ! command -v fly >/dev/null 2>&1; then
    SKIPPED+=("fly secret $name — flyctl not installed")
    warn "flyctl missing; set $name later"
    return 0
  fi
  if [[ -z "${FLY_APP:-}" ]]; then
    SKIPPED+=("fly secret $name — no Fly app named yet")
    warn "no Fly app named; set $name later"
    return 0
  fi
  if printf '%s=%s\n' "$name" "$value" | fly secrets import --stage --app "$FLY_APP" >/dev/null 2>&1; then
    FLY_SET+=("$name")
    printf '  %s✓ staged%s Fly secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("fly secret $name (retry: fly secrets import --stage --app $FLY_APP)")
    warn "could not stage $name"
  fi
}

# require CMD "why" warns once about a missing tool rather than dying mid-run.
require() {
  command -v "$1" >/dev/null 2>&1 && return 0
  warn "$1 is not installed — $2"
  SKIPPED+=("install $1 — $2")
  return 1
}

banner "Recomencemos go-live — runbook 1-5"

say "Provisioning, and the domain warm-up whose clock starts now."
say "Everything here is a step an agent cannot take for you."
note "Source: docs/runbooks/recomencemos-go-live.md, sections 1 to 5"
printf '\n'
warn "Section 4 has a lead time measured in weeks, and its failure is silent."
note "Warming starts at the first deploy, not at the announcement. Do not leave it."
printf '\n'
require fly "sections 1 and 5 set and read Fly secrets and machine size" || true
require dig "section 4 verifies SPF, DKIM and DMARC" || true
require psql "section 2 reads the connection limit and creates the extensions" || true
require curl "section 3 proves the quarantine prefix is not publicly readable" || true
require gh "section 5 fires the needs-triage dispatch" || true
require openssl "section 1 generates two of the eight secrets" || true
pause "Press Enter to begin."

evidence_init

# ══════════════════════════════════════════════════════════════════════════
# 1 — Credentials: eight, and where each lives
# ══════════════════════════════════════════════════════════════════════════

section "1 — Credentials: eight, and where each of them lives"

# ── Stage 1: the Fly app, which every later secret is set against ─────────
stage "Fly: the app the other seven secrets are set against"
say "Nothing in section 1 can be set before an app exists to set it on."
note "The machine arrives with the first deploy; this stage creates the app and region."
ask FLY_APP "Fly app name:"
ask FLY_REGION "Primary region (bog is Bogota; gig is closest with a Postgres story):"
if [[ -n "$FLY_APP" ]]; then
  write_env FLY_APP "$FLY_APP"
  [[ -n "$FLY_REGION" ]] && write_env FLY_REGION "$FLY_REGION"
  if command -v fly >/dev/null 2>&1; then
    if fly status --app "$FLY_APP" >/dev/null 2>&1; then
      say "App already exists."
      run "fly status --app $FLY_APP" -- fly status --app "$FLY_APP"
    elif confirm "Create the Fly app '$FLY_APP' now?"; then
      run "fly apps create $FLY_APP" -- fly apps create "$FLY_APP"
    else
      SKIPPED+=("fly apps create $FLY_APP")
    fi
  fi
else
  SKIPPED+=("Fly app — none named, so no secret below could be staged")
fi

# ── Stage 2: PlanetScale, both connection strings ─────────────────────────
stage "PlanetScale: the pooled string, and the dangerous one"
say "Two strings, and they are not interchangeable: the pooled one and the direct one."
step "PlanetScale, then your database, then Connect."
step "Copy the POOLED string first — that is the one the app runs on."
step "Then the DIRECT string — migrations run on it, and so does Admin recovery."
warn "The direct string has a higher blast radius than any other value here."
note "Treat it as the most dangerous string in the list. Section 1 means that."
open_url "https://app.planetscale.com"
ask PS_DATABASE "Database name (for the record, not a secret):"
[[ -n "$PS_DATABASE" ]] && write_env PS_DATABASE "$PS_DATABASE"
DATABASE_URL=""
DIRECT_DATABASE_URL=""
ask_secret DATABASE_URL "Pooled connection string:"
ask_secret DIRECT_DATABASE_URL "Direct connection string:"
fly_secret DATABASE_URL "$DATABASE_URL"
fly_secret DIRECT_DATABASE_URL "$DIRECT_DATABASE_URL"

# ── Stage 3: Resend, the key and the signing secret ───────────────────────
stage "Resend: the sending key, and the secret that makes a bounce trustworthy"
say "Two values — the sending key, and the signing secret. The second is not optional."
step "Resend, then API Keys. Create a key scoped to SENDING, not full access."
step "Resend, then Webhooks. Create the endpoint, then copy its signing secret."
warn "Without the signing secret a forged bounce is an account-denial primitive."
open_url "https://resend.com/api-keys"
RESEND_API_KEY=""
RESEND_WEBHOOK_SECRET=""
ask_secret RESEND_API_KEY "Resend API key (sending-scoped):"
ask_secret RESEND_WEBHOOK_SECRET "Resend webhook signing secret:"
fly_secret RESEND_API_KEY "$RESEND_API_KEY"
fly_secret RESEND_WEBHOOK_SECRET "$RESEND_WEBHOOK_SECRET"

# ── Stage 4: Cloudflare R2 credentials ────────────────────────────────────
stage "Cloudflare R2: an access key scoped to one bucket"
say "The R2 access key and its secret. The bucket itself is section 3, two stages on."
step "Cloudflare, then R2, then Manage API tokens. Create a token."
step "Scope it to the ONE bucket. A tenancy-wide R2 token is not this value."
open_url "https://dash.cloudflare.com"
R2_ACCESS_KEY_ID=""
R2_SECRET_ACCESS_KEY=""
ask_secret R2_ACCESS_KEY_ID "R2 access key id:"
ask_secret R2_SECRET_ACCESS_KEY "R2 secret access key:"
fly_secret R2_ACCESS_KEY_ID "$R2_ACCESS_KEY_ID"
fly_secret R2_SECRET_ACCESS_KEY "$R2_SECRET_ACCESS_KEY"

# ── Stage 5: Google OAuth ─────────────────────────────────────────────────
stage "Google OAuth: the client, and a redirect URI that matches exactly"
say "The OAuth client behind sign-in with Google in one tap."
step "Google Cloud console, then APIs and Services, then Credentials."
step "Set the authorised redirect URI to your deployed origin's callback path."
warn "The redirect URI must match the deployed origin EXACTLY: scheme, host, path."
note "A mismatch fails at sign-in, not at deploy, which is the worst time to find it."
open_url "https://console.cloud.google.com/apis/credentials"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
ask GOOGLE_CLIENT_ID "Google OAuth client id (public):"
ask_secret GOOGLE_CLIENT_SECRET "Google OAuth client secret:"
[[ -n "$GOOGLE_CLIENT_ID" ]] && fly_secret GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
fly_secret GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── Stage 6: the two generated secrets ────────────────────────────────────
stage "Generated: the auth secret, and the scheduler's shared secret"
say "The auth secret and the scheduler's — the only two you issue yourself, with openssl."
printf '\n'
warn "Rotating the auth secret invalidates every Admin second factor."
note "It encrypts TOTP secrets and backup codes at rest. Rotation is an"
note "operational event with a recovery step attached (section 6), not hygiene."
printf '\n'
BETTER_AUTH_SECRET=""
JOB_SHARED_SECRET=""
if command -v openssl >/dev/null 2>&1; then
  if confirm "Generate the auth secret now (openssl rand -base64 32)?"; then
    BETTER_AUTH_SECRET=$(openssl rand -base64 32)
    show_once "BETTER_AUTH_SECRET" "$BETTER_AUTH_SECRET"
  fi
else
  ask_secret BETTER_AUTH_SECRET "Auth secret (32+ chars):"
fi
fly_secret BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET"

printf '\n'
say "The shared job secret is the eighth, and it belongs to the scheduler in 5b."
note "An older count says seven credentials; the table above says eight. The eighth"
note "arrived with the scheduler, after that count was written, and is offered here"
note "so 5b is not left holding a credential nobody set — skip it if you prefer."
if confirm "Set the shared job secret now as well?"; then
  if command -v openssl >/dev/null 2>&1; then
    JOB_SHARED_SECRET=$(openssl rand -base64 32)
    show_once "JOB_SHARED_SECRET" "$JOB_SHARED_SECRET"
  else
    ask_secret JOB_SHARED_SECRET "Shared job secret (32+ chars):"
  fi
  fly_secret JOB_SHARED_SECRET "$JOB_SHARED_SECRET"
  warn "It must be set IDENTICALLY as a Trigger.dev environment variable."
  note "Rotating one without the other stops every scheduled job. That is 5b."
  SKIPPED+=("shared job secret into Trigger.dev, identical to the Fly secret (5b)")
else
  SKIPPED+=("shared job secret — deferred to the scheduler in section 5b")
fi

# ── Stage 7: mirror, then prove the absence ───────────────────────────────
stage "Mirror to the password manager, then prove none of it is in the repo"
say "A lost machine must not be a lost platform."
warn "The Resend key and the R2 secret are NOT recoverable from Fly, only replaceable."
step "Put all of them in the password manager now, before this screen clears."
pause "Mirrored? Press Enter."
attest "All eight mirrored into the password manager" ||
  SKIPPED+=("mirror the eight secrets into the password manager")

if command -v fly >/dev/null 2>&1 && [[ -n "${FLY_APP:-}" ]]; then
  say "Names and digests only — fly never prints a value back."
  run "fly secrets list --app $FLY_APP" -- fly secrets list --app "$FLY_APP"
fi

printf '\n'
say "Now the other half of the criterion: no .env in this repo holds any of them."
note "turbo.json declares .env* a build input, so such a file is hashed into the"
note "cache key and travels with the artifact under remote caching."
run "find . -name '.env*' -not -path '*/node_modules/*' -not -path './.git/*'" -- \
  find . -name '.env*' -not -path '*/node_modules/*' -not -path './.git/*'
if [[ -n "$(run_value)" ]]; then
  warn "A .env file exists in this checkout."
  note "Gitignored is not enough. turbo.json declares .env* a build input, so the"
  note "file is hashed into the cache key whether git tracks it or not."
  SKIPPED+=("section 1 — remove the .env file(s) listed above")
else
  say "No output at all. That is the pass: this checkout has no .env file."
fi

# Every one of the nine key names, because the criterion says "each key name"
# and a pattern covering four of them proves nothing about the other five.
SECRET_NAMES='DATABASE_URL|DIRECT_DATABASE_URL|RESEND_API_KEY|RESEND_WEBHOOK_SECRET|R2_ACCESS_KEY_ID|R2_SECRET_ACCESS_KEY|GOOGLE_CLIENT_SECRET|BETTER_AUTH_SECRET|JOB_SHARED_SECRET'
run "git grep -nE '($SECRET_NAMES)' || printf '(no matches)\n'" -- \
  sh -c "git grep -nE '($SECRET_NAMES)' || printf '(no matches)\n'"
say "Every line above must be a DECLARATION: a name in turbo.json, a doc mention."
attest "Every grep hit above is a declaration, never a value" ||
  SKIPPED+=("section 1 — a grep hit was a value. Rotate it before anything else")

# ══════════════════════════════════════════════════════════════════════════
# 2 — Database
# ══════════════════════════════════════════════════════════════════════════

section "2 — Database: the connection limit, the extensions, retention, one restore"

# ── Stage 8: the connection limit ─────────────────────────────────────────
stage "Postgres: the connection limit, against the pool cap the app opens"
say "This is the one number nobody could verify before the account existed."
note "It must sit ABOVE the pool cap of 10 connections per machine the app opens."
if [[ -z "${DIRECT_DATABASE_URL:-}" ]]; then
  ask_secret DIRECT_DATABASE_URL "Direct connection string (needed for section 2):"
fi
if command -v psql >/dev/null 2>&1 && [[ -n "${DIRECT_DATABASE_URL:-}" ]]; then
  run "psql \$DIRECT_DATABASE_URL -c 'SHOW max_connections'" -- \
    psql "$DIRECT_DATABASE_URL" -c "SHOW max_connections"
  run "psql \$DIRECT_DATABASE_URL -c 'SHOW superuser_reserved_connections'" -- \
    psql "$DIRECT_DATABASE_URL" -c "SHOW superuser_reserved_connections"
else
  defer "section 2 connection limit" "psql or the direct connection string was unavailable"
fi
CONN_LIMIT=""
ask CONN_LIMIT "The limit your PLAN states (the dashboard number, not just the setting):"
record "Connection limit (plan)" "$CONN_LIMIT"
record "Application pool cap" "10 connections per machine"
attest "The plan's limit sits above 10 per machine" ||
  SKIPPED+=("section 2 — limit at or below the pool cap of 10. The cap changes, or the plan does")

# ── Stage 9: the two extensions ───────────────────────────────────────────
stage "Postgres: citext and pg_trgm"
say "Search that ignores accents, and the case-insensitive unique email, need these."
if command -v psql >/dev/null 2>&1 && [[ -n "${DIRECT_DATABASE_URL:-}" ]]; then
  run "psql \$DIRECT_DATABASE_URL -c 'CREATE EXTENSION IF NOT EXISTS citext'" -- \
    psql "$DIRECT_DATABASE_URL" -c "CREATE EXTENSION IF NOT EXISTS citext"
  CITEXT_STATUS=$RUN_STATUS
  run "psql \$DIRECT_DATABASE_URL -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm'" -- \
    psql "$DIRECT_DATABASE_URL" -c "CREATE EXTENSION IF NOT EXISTS pg_trgm"
  TRGM_STATUS=$RUN_STATUS
  run "psql \$DIRECT_DATABASE_URL -c 'SELECT extname, extversion FROM pg_extension'" -- \
    psql "$DIRECT_DATABASE_URL" -c "SELECT extname, extversion FROM pg_extension ORDER BY extname"
  say "Both must appear in the list above."
  if (( CITEXT_STATUS != 0 || TRGM_STATUS != 0 )); then
    warn "CREATE EXTENSION failed — find the dashboard toggle that makes it succeed."
    note "Section 2 allows either route. What it does not allow is moving on without one."
    SKIPPED+=("section 2 — enable citext and pg_trgm from the PlanetScale dashboard")
  fi
else
  defer "section 2 extensions" "psql or the direct connection string was unavailable"
fi

# ── Stage 10: backup retention ────────────────────────────────────────────
stage "Backups: retention set to 7 days, and not a day fewer"
say "7 days matches retention-backups in docs/policy/."
warn "The deletion copy a Worker reads promises exactly this number."
note "The vendor setting and that sentence must agree, or the deletion copy lies."
open_url "https://app.planetscale.com"
step "PlanetScale, then your database, then Backups. Set retention to 7 days."
pause "Set? Press Enter."
RETENTION_DAYS=""
ask RETENTION_DAYS "Retention now showing in the dashboard (days):"
record "Backup retention (days)" "$RETENTION_DAYS"
if [[ "$RETENTION_DAYS" != "7" ]]; then
  warn "That is not 7."
  SKIPPED+=("section 2 — retention is '$RETENTION_DAYS'; the deletion copy promises 7")
fi

# ── Stage 11: the restore rehearsal ───────────────────────────────────────
stage "Restore: rehearsed once, timed, both stores together"
say "RPO under 1 h and RTO under 4 h are UNPROVEN until this runs once."
warn "Restore both stores together."
note "A recovered photoKey pointing at an R2 object that is gone is a half-recovery"
note "nobody notices until a Worker does."
printf '\n'
step "Restore the most recent backup into a SCRATCH database."
step "Restore the R2 bucket state alongside it."
step "Note the wall-clock time from starting to a database you could serve from."
note "Start your timer now; this stage waits."
pause "Rehearsed? Press Enter."
RESTORE_MINUTES=""
ask RESTORE_MINUTES "Elapsed time, in minutes (this is the RTO):"
record "Restore rehearsal elapsed (minutes)" "$RESTORE_MINUTES"
record "RTO target" "4 h (240 minutes)"
if [[ "$RESTORE_MINUTES" =~ ^[0-9]+$ ]] && (( RESTORE_MINUTES > 240 )); then
  warn "$RESTORE_MINUTES minutes is over the 4 h RTO."
  SKIPPED+=("section 2 — measured restore of ${RESTORE_MINUTES}m exceeds the 4 h RTO")
fi

# Section 2 names both numbers, and both are unproven until this runs once.
# RTO is how long the recovery took; RPO is how much data it lost. Recording
# only the first leaves half the sentence unproven while looking complete.
printf '\n'
say "The other number: how much data the recovered copy was missing."
note "That is the gap between the backup and the moment you restored it."
RESTORE_RPO=""
ask RESTORE_RPO "Data lost, in minutes (this is the RPO):"
record "Observed recovery point (minutes of data lost)" "$RESTORE_RPO"
record "RPO target" "1 h (60 minutes)"
if [[ "$RESTORE_RPO" =~ ^[0-9]+$ ]] && (( RESTORE_RPO > 60 )); then
  warn "$RESTORE_RPO minutes is over the 1 h RPO."
  SKIPPED+=("section 2 — measured recovery point of ${RESTORE_RPO}m exceeds the 1 h RPO")
fi

attest "Both stores were restored together, not the database alone" ||
  SKIPPED+=("section 2 — the rehearsal covered the database only. R2 is the other half")

# ══════════════════════════════════════════════════════════════════════════
# 3 — Object storage
# ══════════════════════════════════════════════════════════════════════════

section "3 — Object storage: the bucket, the quarantine prefix, transformations"

# ── Stage 12: the bucket, and a quarantine prefix that is really closed ───
stage "R2: the bucket, and a quarantine prefix that is not publicly readable"
say "What has to be unreachable is the STORED OBJECT, not merely the page."
warn "A pending photo at a readable URL that nothing links to defeats the rule"
note "while appearing to satisfy it. So this stage ends in a failed request, by design."
open_url "https://dash.cloudflare.com"
step "Cloudflare, then R2. Create the bucket."
step "Create the quarantine prefix and confirm it is in no public bucket path."
ask R2_BUCKET "Bucket name:"
[[ -n "$R2_BUCKET" ]] && write_env R2_BUCKET "$R2_BUCKET"
ask R2_QUARANTINE_URL "A full URL to an object under the quarantine prefix:"
if [[ -n "$R2_QUARANTINE_URL" ]] && command -v curl >/dev/null 2>&1; then
  write_env R2_QUARANTINE_URL "$R2_QUARANTINE_URL"
  say "Requesting it with no credentials at all."
  note "The pass is a real DENIAL — 401, 403 or 404. Not merely 'anything but 200':"
  note "a timeout or an unbound domain also fails to return 200, and proves nothing."
  run "curl -s -o /dev/null -w '%{http_code}' <quarantine-url>" -- \
    curl -s -o /dev/null -w '%{http_code}\n' --max-time 20 "$R2_QUARANTINE_URL"
  # Branch on the bytes that went into the transcript. Asking the human to
  # re-type the code they just saw turns the measurement back into the
  # assertion this ticket's last criterion exists to exclude.
  QCODE=$(run_value)
  printf -- '\n- Quarantine prefix, unauthenticated status: **%s** (measured)\n' \
    "${QCODE:-none}" >> "$EVIDENCE"
  case "$QCODE" in
  401 | 403 | 404)
    say "$QCODE — not served to an unauthenticated request. That is the pass."
    ;;
  200)
    warn "200 means the quarantine prefix IS publicly readable."
    note "The object itself has to be unreachable, and it is not. This is that failure."
    SKIPPED+=("section 3 — quarantine prefix returned 200, so unreviewed photos are readable")
    ;;
  000 | "")
    warn "No HTTP response at all — a timeout, DNS failure, or no bound domain."
    note "This proves nothing either way. It is not a pass."
    SKIPPED+=("section 3 — quarantine check reached nothing ($QCODE). Re-run against a bound URL")
    ;;
  *)
    warn "$QCODE is neither a denial nor a success."
    SKIPPED+=("section 3 — quarantine check was inconclusive ($QCODE). A pass is 401, 403 or 404")
    ;;
  esac
else
  defer "section 3 quarantine non-readability" "no quarantine URL given, so nothing was proven"
fi

# ── Stage 13: the zone, and image transformations ─────────────────────────
stage "Cloudflare: the zone, and image transformations turned on"
say "A dashboard step, and photos serve at full size until it is done."
step "Cloudflare: add your domain as a zone, nameservers pointed at Cloudflare."
step "Then Images: enable transformations for that zone."
open_url "https://dash.cloudflare.com"
pause "Enabled? Press Enter."
attest "Image transformations are enabled on the zone" ||
  SKIPPED+=("section 3 — enable image transformations, or photos serve at full size")
ask IMAGE_HOST "The image host that will appear in the CSP's img-src (section 5):"
[[ -n "$IMAGE_HOST" ]] && write_env IMAGE_HOST "$IMAGE_HOST"

# ══════════════════════════════════════════════════════════════════════════
# 4 — Sending domain. The one with a lead time.
# ══════════════════════════════════════════════════════════════════════════

section "4 — Sending domain: the step whose lead time is measured in weeks"

# ── Stage 14: the domain, and the sending subdomain ───────────────────────
stage "Resend: the sending subdomain"
warn "This is the step that cannot be compressed at the end."
say "Warm-up guidance is 50-100 sends/day in week 1, and 200-500 in week 2."
say "The announcement is a spike onto a domain that has never sent anything."
printf '\n'
step "Resend, then Domains. Add a SUBDOMAIN for sending, not the root domain."
step "Resend shows the DNS records; publish them in the zone from stage 13."
open_url "https://resend.com/domains"
ask ROOT_DOMAIN "Root domain (e.g. example.co):"
ask SENDING_SUBDOMAIN "Sending subdomain (e.g. mail.example.co):"
[[ -n "$ROOT_DOMAIN" ]] && write_env ROOT_DOMAIN "$ROOT_DOMAIN"
[[ -n "$SENDING_SUBDOMAIN" ]] && write_env SENDING_SUBDOMAIN "$SENDING_SUBDOMAIN"
pause "Records published in Cloudflare? Press Enter."

# ── Stage 15: dig, three times, and no assuming ───────────────────────────
stage "DNS: SPF, DKIM and DMARC each verified with dig"
say "Verified, not assumed. Section 4 is explicit about that."
# dig_txt LABEL NAME digs once, and judges the answer that went into the
# transcript. Digging a second time to test what the first one printed would
# let the recorded evidence and the verdict come from different lookups.
dig_txt() {
  local label="$1" name="$2"
  run "dig +short TXT $name" -- dig +short TXT "$name"
  if [[ -z "$(run_value)" ]]; then
    warn "$label did not resolve at $name."
    SKIPPED+=("section 4 — $label did not resolve at $name")
    return 1
  fi
  say "$label resolves."
  return 0
}

if command -v dig >/dev/null 2>&1 && [[ -n "${SENDING_SUBDOMAIN:-}" ]]; then
  dig_txt SPF "$SENDING_SUBDOMAIN" || true
  dig_txt DKIM "resend._domainkey.$SENDING_SUBDOMAIN" || true
  if [[ -n "${ROOT_DOMAIN:-}" ]]; then
    dig_txt DMARC "_dmarc.$ROOT_DOMAIN" || true
  else
    SKIPPED+=("section 4 — no root domain given, so DMARC was never checked")
  fi
  say "All three must print a record. An empty answer is a failure, not a delay."
  note "If one is empty, give DNS a few minutes and re-run this wizard — it resumes."
else
  defer "section 4 DNS verification" "dig is missing, or no sending subdomain was given"
fi

# ── Stage 16: the fallback ────────────────────────────────────────────────
stage "The fallback subdomain, held and warmed in parallel"
say "So a reputation problem on the primary is a DNS change rather than a rebuild."
note "Held and WARMED in parallel — an unwarmed fallback is not a fallback."
ask FALLBACK_SUBDOMAIN "Fallback sending subdomain:"
if [[ -n "$FALLBACK_SUBDOMAIN" ]]; then
  write_env FALLBACK_SUBDOMAIN "$FALLBACK_SUBDOMAIN"
  if command -v dig >/dev/null 2>&1; then
    dig_txt "fallback SPF" "$FALLBACK_SUBDOMAIN" || true
  fi
  # "Held AND warmed in parallel" is one requirement, not two, and holding is
  # the half that leaves a record. An unwarmed fallback fails at the moment it
  # is switched to, which is the moment the primary is already in trouble.
  attest "The fallback is being warmed in parallel, not merely held" ||
    SKIPPED+=("section 4 — the fallback is held but unwarmed, so it is not yet a fallback")
else
  SKIPPED+=("section 4 — no fallback held. A reputation problem becomes a rebuild")
fi

# ── Stage 17: the date the clock started ──────────────────────────────────
stage "Warm-up: the date it started, recorded"
say "The ticket asks for this date specifically, and this is where it exists."
note "Every ticket's test sends count toward the curve. There is no separate"
note "warming exercise to schedule — which is why the date matters more than a plan."
WARMUP_START=""
ask WARMUP_START "Date warming began (YYYY-MM-DD, today if the records just went live):"
[[ -z "$WARMUP_START" ]] && WARMUP_START=$(date -u '+%Y-%m-%d')
write_env WARMUP_START "$WARMUP_START"
record "Domain warm-up started" "$WARMUP_START"
record "Week 1 ceiling" "50-100 sends/day"
record "Week 2 ceiling" "200-500 sends/day"
printf '\n'
step "Write the staged announcement plan: who is told on which day."
note "So volume tracks the curve rather than outrunning it."
attest "A staged announcement plan is written down somewhere durable" ||
  SKIPPED+=("section 4 — write the staged announcement plan; the curve is the constraint")

# ── Stage 18: the check most likely to be faked ───────────────────────────
stage "Deliverability: into real Colombian inboxes, by eye"
warn "This is the check most likely to be ticked without being done."
note "Section 4 says exactly that, and says its failure is silent: sends are"
note "ACCEPTED, not bounced. The share of sign-in links that get used is the only"
note "thing that would reveal it, after the window has closed."
printf '\n'
step "Send to a live gmail.com account. Open it. Inbox or spam?"
step "Send to a live hotmail.com account. Open it. Inbox or spam?"
note "This does NOT gate the announcement — that was decided knowingly."
GMAIL_RESULT=""
HOTMAIL_RESULT=""
ask GMAIL_RESULT "gmail.com landed in (inbox / spam / not sent yet):"
ask HOTMAIL_RESULT "hotmail.com landed in (inbox / spam / not sent yet):"
record "gmail.com placement" "$GMAIL_RESULT"
record "hotmail.com placement" "$HOTMAIL_RESULT"
[[ "$GMAIL_RESULT" == "inbox" ]] || SKIPPED+=("section 4 — gmail placement was '$GMAIL_RESULT'")
[[ "$HOTMAIL_RESULT" == "inbox" ]] || SKIPPED+=("section 4 — hotmail placement was '$HOTMAIL_RESULT'")

# ══════════════════════════════════════════════════════════════════════════
# 5 — Application configuration
#
# FIVE rows, not four. The ticket's fifth acceptance criterion abbreviates this
# section to "a 1 GB Fly machine, an enforced CSP, an uptime probe ... and
# machine bands", inheriting the spec obligations table's one-line summary; the
# runbook itself carries a fifth checkbox, the daily digest (C10). It gets a
# stage of its own below. A section header naming C10 over four stages that
# never touch it would be a transcript claiming coverage it does not have.
#
# Four of the five presuppose a DEPLOYED application, and #7 blocks the ticket
# chain that deploys it (#7 to #8 to #9). None is skipped quietly: each detects
# its own precondition and defers with the reason recorded. Re-run this wizard
# after #9 to close them.
# ══════════════════════════════════════════════════════════════════════════

section "5 — Application configuration: memory, CSP, probe, digest, triage"

# ── Stage 19: machine memory ──────────────────────────────────────────────
stage "Fly: machine memory of at least 1 GB"
if command -v fly >/dev/null 2>&1 && [[ -n "${FLY_APP:-}" ]] && fly status --app "$FLY_APP" >/dev/null 2>&1; then
  run "fly scale show --app $FLY_APP" -- fly scale show --app "$FLY_APP"
  say "Memory must read 1024 MB or more."
  if confirm "Set memory to 1 GB now?"; then
    run "fly scale memory 1024 --app $FLY_APP" -- fly scale memory 1024 --app "$FLY_APP"
  fi
else
  defer "section 5 machine memory of 1 GB" \
    "nothing has deployed yet, and a machine arrives with the first deploy"
fi

# ── Stage 20: the CSP ─────────────────────────────────────────────────────
stage "CSP: shipped and enforced, not report-only"
say "frame-ancestors 'none' is the load-bearing directive."
warn "Without it acceptOffer is clickjackable — one click releasing a displaced"
note "person's name, phone and email."
printf '\n'
say "The directive section 5 fixes, with your two hosts substituted:"
note "  default-src 'self'; frame-ancestors 'none';"
note "  img-src 'self' ${IMAGE_HOST:-<image-host>} data:;"
note "  connect-src 'self' <sentry-ingest>; base-uri 'self'; form-action 'self'"
printf '\n'
note "Next's inline bootstrap needs a nonce or 'strict-dynamic'. Section 5 calls"
note "this the directive most likely to break the first deploy."
if grep -rqs "frame-ancestors" apps/web 2>/dev/null; then
  run "grep -rn frame-ancestors apps/web" -- grep -rn "frame-ancestors" apps/web
  attest "The CSP is enforced, not Content-Security-Policy-Report-Only" ||
    SKIPPED+=("section 5 — the CSP is report-only. Report-only is not a control")
else
  defer "section 5 enforced CSP" \
    "no CSP in apps/web yet; it ships with the app, which has not deployed"
fi

# ── Stage 21: the uptime probe ────────────────────────────────────────────
stage "Uptime: probe every 60 s, alert after 2 consecutive failures"
say "With on-call-rotation at NOBODY, detection latency is the entire mitigation."
ask HEALTH_URL "Deployed health URL (blank if nothing is deployed yet):"
if [[ -n "$HEALTH_URL" ]] && command -v curl >/dev/null 2>&1; then
  write_env HEALTH_URL "$HEALTH_URL"
  run "curl -s -o /dev/null -w '%{http_code}' $HEALTH_URL" -- \
    curl -s -o /dev/null -w '%{http_code}\n' --max-time 20 "$HEALTH_URL"
  step "Point your uptime monitor at it: interval 60 s, alert after 2 failures."
  note "default-availability is 99.5% monthly, measured externally."
  pause "Configured? Press Enter."
  attest "Probe interval is 60 s and it alerts after 2 consecutive failures" ||
    SKIPPED+=("section 5 — uptime probe not at 60 s / 2 consecutive failures")
else
  defer "section 5 uptime probe" \
    "the health route ships with the app, which has not deployed"
fi

# ── Stage 22: the digest, which is the human half of alert-destination ────
stage "Daily digest at 08:00 America/Bogota"
say "The queue depths, and the age of the oldest item, once a day."
note "alert-destination has two halves: human-queue bands reach a person through"
note "this digest, and machine bands reach one through the next stage's issue."
note "Without it, the 24-hour band on the oldest item is a number nobody is told."
if [[ -d packages/notifications ]]; then
  run "ls packages/notifications" -- ls packages/notifications
  step "Confirm one digest arrived at 08:00 America/Bogota."
  step "Confirm it carries the queue depths AND the age of the oldest item."
  attest "A digest arrived at 08:00 America/Bogota carrying both numbers" ||
    SKIPPED+=("section 5 — the daily digest is not arriving, or is missing a number")
else
  defer "section 5 daily digest at 08:00 America/Bogota" \
    "it runs through the notification seam, on the queue-digest schedule from section 5b"
fi

# ── Stage 23: machine bands reach a human, through triage ─────────────────
stage "Machine bands open a needs-triage issue from CI"
say "The destination is fixed: a finding reaches planning only through triage."
note "A breach that arrives as a chat message is a breach nobody owns."
if [[ -f .github/workflows/needs-triage.yml ]]; then
  run "ls -l .github/workflows/needs-triage.yml" -- ls -l .github/workflows/needs-triage.yml
  # The file existing in this checkout is NOT the receiver being live. GitHub
  # registers `repository_dispatch` and `workflow_dispatch` triggers from the
  # DEFAULT BRANCH only, so a dispatch against a workflow that exists on a
  # ticket branch alone is accepted and then runs nothing at all. That failure
  # is silent, which is the one kind this section cannot afford.
  if command -v gh >/dev/null 2>&1; then
    run "gh api repos/{owner}/{repo}/actions/workflows --jq '.workflows[].path'" -- \
      gh api "repos/{owner}/{repo}/actions/workflows" --jq '.workflows[].path'
    case "$RUN_OUTPUT" in
    *".github/workflows/needs-triage.yml"*)
      say "Registered on the default branch. Dispatches will reach it."
      ;;
    *)
      warn "The file is here but GitHub has not registered it."
      note "A repository_dispatch is registered from the default branch only, so"
      note "until the PR that adds this workflow merges, a dispatch is accepted"
      note "and runs nothing. Merge first, then come back to this stage."
      SKIPPED+=("section 5 — needs-triage.yml is not on the default branch yet, so no dispatch reaches it")
      ;;
    esac
  fi
  say "What is left is pointing the vendor at it."
  step "In Sentry: Settings, Integrations, Webhooks (or an Internal Integration)."
  step "Point the alert rule at a repository_dispatch of type control-band-breach."
  note "alert-destination in docs/policy/operability.md is already set to this shape."
  printf '\n'
  if command -v gh >/dev/null 2>&1; then
    warn "The next step OPENS A REAL ISSUE in this repository."
    if confirm "Fire a test dispatch now?"; then
      run "gh api repos/{owner}/{repo}/dispatches -f event_type=control-band-breach ..." -- \
        gh api "repos/{owner}/{repo}/dispatches" \
        -f event_type=control-band-breach \
        -f 'client_payload[band]=Wizard test, not a real breach' \
        -f 'client_payload[observed]=0 errors; fired by scripts/go-live.sh' \
        -f 'client_payload[surface]=n/a' \
        -f 'client_payload[first_check]=Close this issue; it is a receiver test'
      if [[ "$RUN_STATUS" -eq 0 ]]; then
        say "Dispatched. Give Actions a moment, then confirm the issue appeared."
        pause "Press Enter to check."
        run "gh issue list --label needs-triage --limit 5" -- \
          gh issue list --label needs-triage --limit 5
        attest "A needs-triage issue was opened, carrying all four fields" ||
          SKIPPED+=("section 5 — the receiver produced no issue. Check the Actions run")
        note "Close the test issue once you have seen it."
      fi
    else
      SKIPPED+=("section 5 — fire a test dispatch and confirm a needs-triage issue appears")
    fi
  fi
  attest "The vendor alert rule points at this repository's dispatch endpoint" ||
    SKIPPED+=("section 5 — point the alert rule at the repository_dispatch receiver")
else
  defer "section 5 machine bands to needs-triage" \
    ".github/workflows/needs-triage.yml is missing from this checkout"
fi

# ──────────────────────────────────────────────────────────────────────────

{
  printf '\n## Run finished\n\n'
  printf -- '- Finished: %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf -- '- Fly secrets staged this run: %s\n' "${FLY_SET[*]:-none}"
  if (( ${#DEFERRED[@]} )); then
    printf -- '\n### Deferred, with reasons\n\n'
    for d in "${DEFERRED[@]}"; do printf -- '- %s\n' "$d"; done
  fi
  if (( ${#SKIPPED[@]} )); then
    printf -- '\n### Still open\n\n'
    for s in "${SKIPPED[@]}"; do printf -- '- %s\n' "$s"; done
  fi
} >> "$EVIDENCE"

finish

if (( ${#FLY_SET[@]} )); then
  note "staged ${#FLY_SET[@]} Fly secret(s): ${FLY_SET[*]}"
  warn "Staged, not deployed. They apply on the next deploy."
  note "  fly secrets deploy --app ${FLY_APP:-<app>}   # once a machine exists"
fi
printf '\n'
note "The transcript is at $EVIDENCE — a command and its output for every check."
note "Paste it on the ticket. A criterion ticked with no evidence is a claim."
if (( ${#DEFERRED[@]} )); then
  printf '\n'
  warn "${#DEFERRED[@]} row(s) deferred because nothing is deployed yet."
  note "Re-run this wizard once the app has deployed; it resumes from $ENV_FILE."
fi
printf '\n'
note "Not covered here — the runbook's second half: 5b the scheduler,"
note "6 the Admin, 7 Ley 1581, 8 branch protection, 9 security review,"
note "10 the announcement gate, 11 the user-measured latency figure."
