#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# docs/runbooks/ui-proof-artifacts.md, sections 1 to 5.
#
# ADR-0019 makes a Build session publish recorded proof of a visible change, and
# nothing in the pipeline creates the place it goes. `scripts/ui-proof.mjs`
# refuses with exit 1 and names that runbook when the bucket or its credentials
# are absent, so until a human has worked it, `--dry-run` is the only form of
# `pnpm ui-proof publish` that works at all. This is that human's hour.
#
# Two deviations from the go-live wizard beside it, both deliberate:
#
#   1. ENV_FILE *is* an env file here, and it is `apps/web/.env.local`. That is
#      the one place this repository already sanctions a real development
#      credential -- `.env.example` says so of `RESEND_API_KEY` and of
#      `GOOGLE_CLIENT_SECRET` in as many words -- and it is gitignored, so the
#      rule the security policy states ("no secret in a repo .env") is about the
#      committed example rather than about this file. The go-live wizard writes
#      no env file at all because its secrets belong to a deploy; these five
#      belong to one operator's machine and are read by a script that runs on it.
#
#      The cost is named rather than hidden: a fresh worktree has no `.env.local`
#      at all, and `pnpm ui-proof publish` runs from the worktree. So stage 6
#      also prints the five values as an `export` block, once, for whoever would
#      rather keep them in the shell where every tree can see them.
#
#   2. Every check is a real command whose output is read. `run` executes, shows
#      and captures; a stage then branches on the bytes rather than on a second
#      run or on a value re-typed by the person being checked. There is no
#      evidence transcript, because there is no ticket asking for one -- and
#      because two of the five values would end up in it.
#
# These helpers live BELOW the marker on purpose: the library above it is
# identical in every wizard and is never hand-edited.

ROOT=$(git rev-parse --show-toplevel 2>/dev/null || printf '%s' "$PWD")
ENV_FILE="${ENV_FILE:-$ROOT/apps/web/.env.local}"

BUCKET_DEFAULT="recomencemos-ui-proof"
RULE_NAME="expire-review-artifacts"

# The five, named once. Both the env write and the printed block iterate this, so
# a sixth value is added in one place and cannot end up in the file while missing
# from the block a worktree depends on -- which is the shape of the bug a hand
# copy of a five-item list eventually has.
KEYS=(
  UI_PROOF_S3_ENDPOINT
  UI_PROOF_S3_BUCKET
  UI_PROOF_S3_ACCESS_KEY_ID
  UI_PROOF_S3_SECRET_ACCESS_KEY
  UI_PROOF_PUBLIC_BASE
)

RUN_STATUS=0
RUN_OUTPUT=""

# `wrangler` if it is installed, `npx` otherwise. Deliberately unpinned: this
# talks to a live Cloudflare account, so the newest client is the one whose
# command surface matches the dashboard the human is looking at.
if command -v wrangler >/dev/null 2>&1; then
  WRANGLER=(wrangler)
else
  WRANGLER=(npx --yes wrangler@latest)
fi

# run "shown command" -- argv...
#
# The shown string and the executed argv are separate so a value passed as an
# argument need not reach the screen. Always returns 0; the status lands in
# $RUN_STATUS and the output in $RUN_OUTPUT, so `set -e` cannot end the wizard
# halfway through a stage.
# **Two defences against colour, and they are the ones `dev-origin.mjs` already
# carries** -- this wizard branches on the bytes of a child's output, which is the
# same shape of parse and the same quiet wrong answer when it breaks. `wrangler`
# colours when `FORCE_COLOR` is in its environment, which dev shells and CI images
# set, and an escape landing inside a URL or beside a word turns a match into a
# no-match. Then the account id is "not found", or the origin is, and the wizard
# reports a step it did not do.
#
#   1. `NO_COLOR` for the child, with `FORCE_COLOR` removed. Clients read
#      `NO_COLOR` ahead of `FORCE_COLOR` and ahead of any stdio test, so this is a
#      promise rather than an inference about how a pipe is detected.
#   2. The escapes are stripped before the output is stored, so a later release
#      that colours a line it was asked not to still parses.
run() {
  local shown="$1"; shift
  [[ "${1:-}" == "--" ]] && shift
  local out status
  printf '  %s$ %s%s\n' "$DIM" "$shown" "$RESET"
  set +e
  out=$(env -u FORCE_COLOR NO_COLOR=1 "$@" 2>&1)
  status=$?
  set -e
  out=$(printf '%s' "$out" | sed $'s/\033\\[[0-9;?]*[a-zA-Z]//g')
  printf '%s\n' "$out" | sed 's/^/    /'
  RUN_STATUS=$status
  RUN_OUTPUT="$out"
  return 0
}

# wr <args...> runs wrangler through `run`, showing the command as a human would
# type it rather than as whichever launcher this machine happens to need.
wr() { run "wrangler $*" -- "${WRANGLER[@]}" "$@"; }

# show_exports prints the five values as a shell block, once, so they can go into
# a password manager and into a shell that every worktree shares.
#
# It exists because `$ENV_FILE` is per-tree and this pipeline is not: a fresh
# worktree starts with no `.env.local`, and the publish step runs from there.
show_exports() {
  printf '\n  %s%s╔══ the five values — shown once ══%s\n' "$BOLD" "$YELLOW" "$RESET"
  local key
  for key in "${KEYS[@]}"; do
    printf '  %s%s║%s  export %s="%s"\n' "$BOLD" "$YELLOW" "$RESET" "$key" "${!key:-}"
  done
  printf '  %s%s╚══════════════════════════════════%s\n\n' "$BOLD" "$YELLOW" "$RESET"
}

# require CMD "why" warns once about a missing tool rather than dying mid-run.
require() {
  command -v "$1" >/dev/null 2>&1 && return 0
  warn "$1 is not installed — $2"
  SKIPPED+=("install $1 — $2")
  return 1
}

banner "The artifact store — recorded proof needs somewhere to live"

say "One bucket, two lifetime rules, one public origin and one credential."
say "Everything here is a step an agent may not take: provisioning, and a key."
note "Source: docs/runbooks/ui-proof-artifacts.md, sections 1 to 5"
printf '\n'
warn "One of these steps is not reversible by editing a file afterwards."
note "A lifecycle rule that reaches the durable prefix deletes story demos, and"
note "there is no second copy of one anywhere. Stage 3 is where that is decided."
printf '\n'
require node "the publisher and its dry run are Node scripts" || true
require gh "the publish step reads and rewrites a pull request body" || true
require curl "stage 8 proves the published link is readable by a stranger" || true
require git "the capture directory is resolved from the tree you are in" || true
pause "Press Enter to begin."

# ══════════════════════════════════════════════════════════════════════════
# 1 — The account every later command is run against
# ══════════════════════════════════════════════════════════════════════════

stage "Cloudflare: the account, and the endpoint built from it"
say "R2 speaks S3, and the S3 endpoint is your account id inside a hostname."
say "Nothing below can be created before wrangler knows which account to use."
note "On a first run wrangler opens a browser to authorise itself."
wr whoami
if (( RUN_STATUS != 0 )); then
  warn "wrangler could not say who you are."
  step "Run 'wrangler login' in another terminal, then come back."
  pause "Press Enter when it reports an account."
  # Asked again rather than read again. $RUN_OUTPUT still holds the *failure*,
  # and parsing that would take the id from the one output guaranteed not to
  # carry it -- losing the endpoint precisely when the operator had just fixed
  # the thing that produces it.
  say "Asking again:"
  wr whoami
fi

# The id is 32 hex characters, and `whoami` prints it in a table whose columns
# have moved between wrangler majors — so it is offered rather than taken. A
# single unambiguous match becomes the fallback for an empty answer.
#
# `|| true` is load-bearing rather than defensive, and it is the exact case this
# grep exists for: under `pipefail` a no-match `grep` fails the pipeline, an
# assignment takes the substitution's status, and `set -e` then ends the wizard
# where a *missing* id is the ordinary state -- not signed in, or a wrangler
# whose table no longer prints a bare one. Without it the run dies with nothing
# on screen, one line after telling the operator to come back.
ACCOUNT_GUESS=$(printf '%s' "$RUN_OUTPUT" | grep -oE '[0-9a-f]{32}' | sort -u | head -n1) || true

# A re-run has no CF_ACCOUNT_ID in the env file -- it is not one of the five --
# but it does have the endpoint that was built from it, so the id is recovered
# from there rather than retyped. `ask`'s own default only reaches keys the file
# holds, which this one deliberately is not.
PRIOR_ENDPOINT=$(_existing UI_PROOF_S3_ENDPOINT || true)
if [[ -z "$ACCOUNT_GUESS" && -n "$PRIOR_ENDPOINT" ]]; then
  ACCOUNT_GUESS=$(printf '%s' "$PRIOR_ENDPOINT" | grep -oE '[0-9a-f]{32}' | head -n1) || true
  [[ -n "$ACCOUNT_GUESS" ]] && note "recovered from the endpoint already in $ENV_FILE"
fi
[[ -n "$ACCOUNT_GUESS" ]] && note "an account id to use: $ACCOUNT_GUESS"
ask CF_ACCOUNT_ID "Cloudflare account id:"
[[ -z "$CF_ACCOUNT_ID" ]] && CF_ACCOUNT_ID="$ACCOUNT_GUESS"

if [[ -z "$CF_ACCOUNT_ID" ]]; then
  SKIPPED+=("the account id — the S3 endpoint is built from it and nothing else supplies it")
  warn "No account id, so the endpoint below cannot be built."
else
  UI_PROOF_S3_ENDPOINT="https://${CF_ACCOUNT_ID}.r2.cloudflarestorage.com"
  say "Endpoint: $UI_PROOF_S3_ENDPOINT"
  note "Stage 6 writes it. It is not a secret; the token in stage 5 is."
fi

# ══════════════════════════════════════════════════════════════════════════
# 2 — The bucket (runbook section 1)
# ══════════════════════════════════════════════════════════════════════════

stage "The bucket: one, in the account that holds the rest of this product"
say "Leave the location hint automatic. Nothing here is latency-sensitive —"
say "a reviewer opens the page once."
ask UI_PROOF_S3_BUCKET "Bucket name [$BUCKET_DEFAULT]:"
[[ -z "$UI_PROOF_S3_BUCKET" ]] && UI_PROOF_S3_BUCKET="$BUCKET_DEFAULT"

wr r2 bucket info "$UI_PROOF_S3_BUCKET"
if (( RUN_STATUS == 0 )); then
  say "That bucket already exists, so this stage has nothing to create."
elif confirm "Create the bucket '$UI_PROOF_S3_BUCKET' now?"; then
  wr r2 bucket create "$UI_PROOF_S3_BUCKET"
  (( RUN_STATUS == 0 )) || SKIPPED+=("create the bucket $UI_PROOF_S3_BUCKET")
else
  SKIPPED+=("create the bucket $UI_PROOF_S3_BUCKET")
fi
pause

# ══════════════════════════════════════════════════════════════════════════
# 3 — The two lifetime rules (runbook section 2)
# ══════════════════════════════════════════════════════════════════════════

stage "The two lifetime rules, and they are not symmetric"
say "review/  deleted 30 days after upload. Review proof answers 'did you check"
say "         this', and that answer is spent once the pull request is merged."
say "demos/   no rule at all. A story demo answers 'what does this look like"
say "         working', which is a question that starts at merge."
printf '\n'
warn "A rule with a blank prefix reaches both, and deletes the half that has no"
warn "second copy anywhere. The read-back below is the check, not a formality."
printf '\n'

# The rule name and the prefix are POSITIONAL arguments, not flags. The runbook
# wrote them as `--name` and `--prefix` until this wizard was authored, and
# wrangler's own help is what corrected it; that correction ships with this file.
# `--force` skips wrangler's own confirmation, and that is required rather than
# impatient: this call runs inside `run`, whose output is captured in a command
# substitution, so an interactive prompt there would block on a terminal it
# cannot reach. The gate is the wizard's own confirm above, which a person
# answers on a screen that is theirs.
if confirm "Add the 30-day expiry rule on the review/ prefix?"; then
  wr r2 bucket lifecycle add "$UI_PROOF_S3_BUCKET" "$RULE_NAME" "review/" \
    --expire-days 30 --force
  (( RUN_STATUS == 0 )) || SKIPPED+=("the review/ lifecycle rule on $UI_PROOF_S3_BUCKET")
else
  SKIPPED+=("the review/ lifecycle rule on $UI_PROOF_S3_BUCKET")
fi

say "Reading the rules back:"
wr r2 bucket lifecycle list "$UI_PROOF_S3_BUCKET"

# A listing that could not be produced is not a listing of no rules, and the two
# would otherwise reach the operator as the same warning. This stage is the one
# whose failure cannot be undone by waiting, so it refuses to reach an answer it
# does not have.
if (( RUN_STATUS != 0 )); then
  warn "The rules could not be read, so nothing here has been checked."
  warn "That is not the same as finding no rules, and it is not a pass."
  SKIPPED+=("verifying the lifecycle rules — the listing could not be read")
elif printf '%s' "$RUN_OUTPUT" | grep -q 'review/'; then
  say "Something in that listing names review/. That is all the grep proves:"
  say "it cannot tell you whether a SECOND rule is also there with no prefix."
else
  warn "Nothing there names review/, so review proof would never expire."
fi

# The listing's exact layout is a wrangler detail this wizard has not pinned, so
# the grep above is a hint and the human's read is the check -- which is what the
# runbook means by the list call being the check rather than a formality. Two
# questions, because one compound question is answered about its easier half:
# a blank-prefix rule is the unrecoverable failure, and it hides *beside* a
# correct one rather than instead of it.
if ! confirm "Is every rule listed above scoped to a prefix, with none left blank?"; then
  warn "A blank prefix expires the story demos, which have no second copy."
  step "Dashboard: R2 → the bucket → Settings → Object lifecycle rules."
  step "Delete any rule whose prefix is empty."
  SKIPPED+=("the lifecycle rules — a rule with no prefix was still listed")
  pause "Press Enter when every rule shows a prefix."
fi
if ! confirm "Is the one that expires objects scoped to review/ ?"; then
  warn "Fix it before you leave this stage."
  SKIPPED+=("the lifecycle rules — the expiry rule is not scoped to review/")
  pause "Press Enter when the expiry rule shows the review/ prefix."
fi

# ══════════════════════════════════════════════════════════════════════════
# 4 — Public read, and what that means (runbook section 3)
# ══════════════════════════════════════════════════════════════════════════

stage "Public read: a reviewer, and anyone else holding the link"
say "The bucket will serve unauthenticated reads. That is the same shape"
say "GitHub's own attachments have, and it is why the publisher generates an"
say "unguessable prefix segment rather than a tidy one."
printf '\n'
warn "Read 'What a published artifact may never contain' before enabling it."
note "docs/policy/security.md. Three rules, and this is the step that makes them"
note "true rather than advisory: the enrolment route carries a live credential in"
note "a path segment and a recording captures the address bar, every capture runs"
note "against seeded fixtures because a name or a face in a published artifact is"
note "personal data leaving the system, and a mistake in a durable artifact is"
note "permanent — its only remedy is deletion by hand from the bucket."
printf '\n'
ENABLED_THIS_RUN=0
if confirm "Have you read that section, and enable public read now?"; then
  wr r2 bucket dev-url enable "$UI_PROOF_S3_BUCKET"
  if (( RUN_STATUS == 0 )); then
    ENABLED_THIS_RUN=1
  else
    SKIPPED+=("enable public read on $UI_PROOF_S3_BUCKET")
  fi
else
  SKIPPED+=("enable public read on $UI_PROOF_S3_BUCKET — every published link would 404")
fi

say "Reading the public origin back:"
wr r2 bucket dev-url get "$UI_PROOF_S3_BUCKET"
# `|| true` for the reason given at the account id above, and this site is the
# worse of the two: a custom domain rather than an r2.dev one matches nothing,
# which is a supported answer to the question this stage asks -- and a run that
# ended here would lose the token stage 5 has not collected yet.
DEV_URL=$(printf '%s' "$RUN_OUTPUT" | grep -oE 'https://[A-Za-z0-9.-]+\.r2\.dev' | head -n1) || true

# An origin in that output is not the same fact as a bucket that serves it: the
# subcommand reports the URL and its status together, so a disabled bucket still
# prints a hostname. Offered as the default it produces the one failure the
# runbook calls hardest to diagnose -- an upload reporting success behind a link
# that 404s.
#
# So the guess needs a POSITIVE signal, and matching the word "disabled" is not
# one: that is a denylist over output this wizard has not pinned, and every
# spelling it has not thought of ("Public access: off") reads as permission. The
# two signals it will accept are an `enable` that returned 0 in this same run, or
# a listing that says enabled and does not also say otherwise. Anything else
# keeps the URL on screen as information and refuses to prefill it.
if [[ -n "$DEV_URL" ]]; then
  SAYS_ENABLED=0
  if printf '%s' "$RUN_OUTPUT" | grep -qi 'enabled' &&
    ! printf '%s' "$RUN_OUTPUT" | grep -qi 'not enabled\|disabled'; then
    SAYS_ENABLED=1
  fi
  if (( ENABLED_THIS_RUN == 1 || SAYS_ENABLED == 1 )); then
    note "origin found, and that output reads as enabled: $DEV_URL"
  else
    warn "That output names an origin but does not say public access is on."
    warn "Not prefilling it: a link built on a private bucket 404s while the"
    warn "upload reports success. Paste it yourself if you know it is served."
    DEV_URL=""
  fi
fi
say "A custom domain works too; whichever you chose, its origin is the value."
ask UI_PROOF_PUBLIC_BASE "Public base URL, no trailing slash:"
[[ -z "$UI_PROOF_PUBLIC_BASE" ]] && UI_PROOF_PUBLIC_BASE="$DEV_URL"
UI_PROOF_PUBLIC_BASE="${UI_PROOF_PUBLIC_BASE%/}"
[[ -z "$UI_PROOF_PUBLIC_BASE" ]] &&
  SKIPPED+=("the public base URL — an upload can succeed and still have nowhere to link")

# ══════════════════════════════════════════════════════════════════════════
# 5 — The credential (runbook section 4)
# ══════════════════════════════════════════════════════════════════════════

stage "The credential: one token, this bucket, Object Read & Write"
say "There is no wrangler command for this one. An R2 API token is issued from"
say "the dashboard, and it is the only step here that has to be a browser."
printf '\n'
step "R2 → API → Manage API tokens → Create Account API token."
step "Permission: Object Read & Write, and nothing else."
step "Scope it to this bucket alone: $UI_PROOF_S3_BUCKET"
step "Create it, then copy the Access Key ID and the Secret Access Key."
printf '\n'
warn "The secret is shown once and cannot be printed back. Put it in the"
warn "password manager before you leave that page."
open_url "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
pause "Press Enter when you have both halves on screen."
ask UI_PROOF_S3_ACCESS_KEY_ID "Access Key ID:"
ask_secret UI_PROOF_S3_SECRET_ACCESS_KEY "Secret Access Key (hidden):"
[[ -z "$UI_PROOF_S3_ACCESS_KEY_ID" || -z "$UI_PROOF_S3_SECRET_ACCESS_KEY" ]] &&
  SKIPPED+=("the R2 token — the publisher refuses before its first network call without both halves")
printf '\n'
note "No CI secret is needed, and that is deliberate: captures are local and"
note "gitignored, so CI never sees them and never uploads. The expiry workflow"
note "only rewrites a line in a pull request body, on GITHUB_TOKEN alone."

# ══════════════════════════════════════════════════════════════════════════
# 6 — Where the five values land
# ══════════════════════════════════════════════════════════════════════════

stage "Where the five values live"
say "This tree's env file: $ENV_FILE"

if [[ ! -f "$ENV_FILE" ]]; then
  warn "That file does not exist, and this wizard will not create a partial one."
  note "A file holding only these five would start the app with no database URL"
  note "and no auth secret, which fails in a way that looks like a code problem."
  step "cp apps/web/.env.example apps/web/.env.local"
  if confirm "Copy the example into place now?"; then
    cp "$ROOT/apps/web/.env.example" "$ENV_FILE" &&
      printf '  %s✓ copied%s the example → %s\n' "$GREEN" "$RESET" "$ENV_FILE"
  fi
fi

if [[ -f "$ENV_FILE" ]]; then
  for KEY in "${KEYS[@]}"; do
    [[ -n "${!KEY:-}" ]] && write_env "$KEY" "${!KEY}"
  done
  chmod 600 "$ENV_FILE" 2>/dev/null || true
  note "That file is gitignored, and the publisher reads it because the pnpm"
  note "script passes --env-file-if-exists, the same way db:migrate does."
  note "Editing it invalidates the web build cache, which costs seconds and is"
  note "not a sign anything is wrong: turbo declares .env* a build input."
else
  SKIPPED+=("writing the five values — there is no env file in this tree")
fi

printf '\n'
warn "A fresh worktree has no .env.local, and the publish step runs from one."
say "So here they are as a shell block. Put it in the password manager, and in"
say "a shell file outside the repository if you would rather every tree see it."
show_exports
step "Copy it NOW, before the next stage clears the screen."
pause "Copied? Press Enter."

# ══════════════════════════════════════════════════════════════════════════
# 7 — Prove it: the dry run (runbook section 5)
# ══════════════════════════════════════════════════════════════════════════

stage "Prove it, part one: the dry run, which reaches nothing"
say "The test suite drives this form and only this form, so it is the half"
say "already covered. Running it here separates a naming or capture problem"
say "from a credential one, before any network call happens."
printf '\n'

CAPTURES="$ROOT/.artifacts/ui-proof"
mkdir -p "$CAPTURES"
say "Capture directory: $CAPTURES"
if [[ -z "$(ls -A "$CAPTURES" 2>/dev/null)" ]]; then
  warn "Nothing captured yet, and a placeholder will not do: anything under"
  warn "1024 bytes is refused, because that is what a recording interrupted by"
  warn "a missing ffmpeg leaves behind."
  step "Start the app in another terminal:  pnpm dev"
  step 'agent-browser open "$(pnpm --silent dev:origin)"'
  step "agent-browser screenshot $CAPTURES/before-smoke.png"
  step "Take an after-smoke.png too, so the comparison page has both halves."
  printf '\n'
  warn "Do not name a smoke capture demo-anything. That prefix has no lifecycle"
  warn "rule, so it would sit in the bucket permanently."
  pause "Press Enter when there is a real capture in that directory."
fi

DRY_RUN_STATUS=1
ask PR_NUMBER "A pull request number you own, to publish against:"
if [[ -n "$PR_NUMBER" ]]; then
  run "pnpm ui-proof publish --pr $PR_NUMBER --dry-run" -- \
    pnpm ui-proof publish --pr "$PR_NUMBER" --dry-run
  DRY_RUN_STATUS=$RUN_STATUS
  (( DRY_RUN_STATUS == 0 )) ||
    warn "That refused. Fix what it named before the real publish below."
else
  SKIPPED+=("the end-to-end proof — no pull request number was given")
fi
pause

# ══════════════════════════════════════════════════════════════════════════
# 8 — Prove it: the upload, and the stranger's fetch
# ══════════════════════════════════════════════════════════════════════════

stage "Prove it, part two: the one call the test suite cannot make"
PUBLISHED_STATUS=1
if [[ -z "${PR_NUMBER:-}" ]]; then
  warn "No pull request number, so there is nothing to publish against."
  note "Re-run this wizard once you have one; every value above is remembered."
elif (( DRY_RUN_STATUS != 0 )); then
  # The dry run answers naming, grouping and the capture floor, and it reaches
  # nothing. Offering the upload after it refused would spend a real credential
  # and a real pull request body to be told the same thing again.
  warn "The dry run refused, so there is nothing worth uploading yet."
  note "Fix what it named, then re-run this wizard; the values are remembered."
  SKIPPED+=("the real publish — the dry run refused first")
else
  say "This uploads, then edits the pull request body. It is the only call in"
  say "the whole pipeline that touches the store."
  if confirm "Publish for real against pull request $PR_NUMBER?"; then
    run "pnpm ui-proof publish --pr $PR_NUMBER" -- pnpm ui-proof publish --pr "$PR_NUMBER"
    PUBLISHED_STATUS=$RUN_STATUS
  else
    SKIPPED+=("the real publish — the store's one write path is still unexercised")
  fi
fi

if (( PUBLISHED_STATUS == 0 )); then
  printf '\n'
  say "Four things to confirm, in this order. The first one is a command."
  ask ARTIFACT_URL "Paste the link from the pull request body:"
  if [[ -n "$ARTIFACT_URL" ]]; then
    run "curl -sSL -o /dev/null -w '%{http_code}' $ARTIFACT_URL" -- \
      curl -sSL -o /dev/null -w '%{http_code}' "$ARTIFACT_URL"
    # The code is taken from the END of the captured output rather than compared
    # to the whole of it: `run` merges stderr, and `-sS` keeps curl quiet only
    # while nothing goes wrong -- so a single diagnostic line would otherwise
    # turn a 200 into a failure report. `-L` because a public bucket origin is
    # entitled to redirect.
    HTTP_CODE=$(printf '%s' "$RUN_OUTPUT" | tr -d '[:space:]' | grep -oE '[0-9]{3}$') || true
    if [[ "$HTTP_CODE" == "200" ]]; then
      say "200 — a request carrying no credential can read it."
    else
      warn "That did not answer 200. Either the bucket is still private, or the"
      warn "public base is not the origin that public access produced."
      SKIPPED+=("the unauthenticated read — the published link did not answer 200")
    fi
    open_url "$ARTIFACT_URL"
  else
    SKIPPED+=("the unauthenticated read — no link was pasted to check")
  fi

  # Each of the three records its own No. A question whose only consequence is a
  # warning that scrolls away is a question the closing summary reports as done,
  # which is the failure this whole stage exists to be the opposite of.
  confirm "Does the page render the pull request's own prose?" || {
    warn "An empty body means gh sent the wrong flag: the report looks structurally fine and says nothing."
    SKIPPED+=("the report renders the pull request's prose — it did not")
  }
  confirm "If you captured a video, does it play with controls?" || {
    note "If you captured no video, this one is not a finding."
    SKIPPED+=("a video plays with controls — unanswered or no")
  }
  confirm "Do both prefixes hold what they should, each with its own page?" || {
    warn "The durable half has a viewer of its own on purpose: a page under review/ would be deleted out from under the clips it renders."
    SKIPPED+=("both prefixes hold what they should — they did not")
  }
fi
pause

# ══════════════════════════════════════════════════════════════════════════
# 9 — The half that runs when nobody is watching
# ══════════════════════════════════════════════════════════════════════════

stage "The expiry path, which is the step most likely to be silently wrong"
say "Nothing else fails when this is misconfigured. The bucket's rule deletes"
say "the objects either way; this is what stops a merged pull request spending"
say "the rest of its life pointing at a link that 404s."
printf '\n'
step "Close the pull request you just published to."
step "Watch the body's line rewrite itself to say the artifact expired."
note "That is .github/workflows/ui-proof-expire.yml. It needs pull-requests:"
note "write, and it runs from the base branch rather than from the pull request."
printf '\n'
if [[ -n "${PR_NUMBER:-}" ]]; then
  pause "Press Enter once the pull request is closed."
  say "This prints the block the workflow should have written:"
  run "pnpm ui-proof expire --pr $PR_NUMBER --dry-run" -- \
    pnpm ui-proof expire --pr "$PR_NUMBER" --dry-run
  say "Compare it with what is on the pull request now. If the body still shows"
  say "the live link, the workflow did not run."
  confirm "Does the body already say the artifact is no longer linked?" ||
    SKIPPED+=("the expiry workflow — it did not rewrite the body on close")
fi

finish
